export enum Authority {
  ADMIN = 'ROLE_ADMIN',
  USER = 'ROLE_USER',
  CONTRIBUTEUR = "ROLE_CONTRIBUTEUR",
  ANIMATEURCENTRAL = "ROLE_ANIMATEUR_CENTRAL",
  RELAISCENTRAL = "ROLE_RELAIS_CENTRAL",
  RELAISREGIONAL = "ROLE_RELAIS_REGIONAL"
}
